Repository ProjectsUniversity/COSC360, pull requests merged in 2025-02, with the labels that each got.

#7 Add signup.html
  html/signup.html
Labels: basic task

#9 Add Login
  html/login.html
Labels: basic task

#11 Add job application and job swipe feature pages
  html/apply.html
  html/homepage.html
Labels: basic task

#14 HOTFIX: Added Bootstrap dependency
  package-lock.json
  package.json
Labels: hotfix

#16 Added TailwindCSS
  package-lock.json
  package.json
  postcss.config.js
  src/App.jsx
  src/styles/index.css
Labels: new feature

#18 Port signup.html to SignUp.jsx
  html/signup.html
  src/App.jsx
  src/components/SignUp.jsx
  src/main.jsx
  src/styles/index.css
Labels: new feature

#20 Remove TailwindCSS in favour of Vanilla CSS
  package-lock.json
  package.json
  postcss.config.js
  src/App.jsx
  src/components/SignUp.jsx
  src/styles/SignUp.css
  src/styles/index.css
Labels: hotfix

#21 Created basic HTML CSS for user profile page
  html/userprofile.html
Labels: basic task
